apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: ufosc-cert
spec:
  domains:
    - ufosc.org
    - www.ufosc.org
    - api.testing.ufosc.org
    - auth.testing.ufosc.org
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
 name: ufosc-fe-config
spec:
  redirectToHttps:
    enabled: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ufosc-ingress
  annotations:
    ingressClassName: "gce"
    kubernetes.io/ingress.global-static-ip-name: oscwebsite
    networking.gke.io/managed-certificates: ufosc-cert
    networking.gke.io/v1beta1.FrontendConfig: ufosc-fe-config
spec:
  rules:
    - host: ufosc.org
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: osc-website-service
                port:
                  number: 3002
    - host: www.ufosc.org
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: osc-website-service
                port:
                  number: 3002
    - host: api.testing.ufosc.org
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: oauth2-service-server
                port:
                  number: 8080
    - host: auth.testing.ufosc.org
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: oauth2-service-dashboard
                port:
                  number: 3000
