apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-server
  labels:
    app: oauth2-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-server
  template:
    metadata:
      labels:
        app: oauth2-server
    spec:
      containers:
        - name: oauth2-backend
          #image: oauth2
          #imagePullPolicy: Never
          image: us-central1-docker.pkg.dev/innate-concept-409007/docker-repo/oauth2:v0.1.4
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb-service.default.svc.cluster.local:27017"
            - name: GIN_MODE
              value: "debug"
            - name: DB_NAME
              value: "oauth2-testing"
            - name: NOTIF_EMAIL_ADDR
              value: "no-reply.notifications@ufosc.org"
            - name: WEBSMTP
              value: "http://websmtp-service.default.svc.cluster.local:3001/mail/send"
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: secret
            - name: PORT
              value: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-dashboard
  labels:
    app: oauth2-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-dashboard
  template:
    metadata:
      labels:
        app: oauth2-dashboard
    spec:
      containers:
        - name: oauth2-dashboard
          image: us-central1-docker.pkg.dev/innate-concept-409007/docker-repo/dashboard:v0.1.4
          #imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-service-server
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: oauth2-server
spec:
  #type: NodePort
  selector:
    app: oauth2-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      #nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-service-dashboard
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: oauth2-dashboard
spec:
  #type: NodePort
  selector:
    app: oauth2-dashboard
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      #nodePort: 30002
