apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-server
  labels:
    app: oauth2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2
  template:
    metadata:
      labels:
        app: oauth2
    spec:
      containers:
        - name: oauth2-backend
          image: oauth2
          #imagePullPolicy: Never
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb-service.default.svc.cluster.local:27017"
            - name: GIN_MODE
              value: "debug"
            - name: DB_NAME
              value: "oauth2-testing"
            - name: NOTIF_EMAIL_ADDR
              value: "no-reply.notifications@ufosc.org"
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: secret
            - name: PORT
              value: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-dashboard
  labels:
    app: oauth2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2
  template:
    metadata:
      labels:
        app: oauth2
    spec:
      containers:
        - name: oauth2-dashboard
          image: dashboard
          #imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-service-server
  labels:
    app: oauth2
spec:
  #type: NodePort
  selector:
    app: oauth2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      #nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-service-dashboard
  labels:
    app: oauth2
spec:
  #type: NodePort
  selector:
    app: oauth2
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      #nodePort: 30002
