import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from "@/app/chakra";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'OSC OAuth2 Frontend',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{width: '100vw', height: '100vh'}}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
