name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build OAuth2
      run: cd oauth2 && go build -v ./...

    - name: Vet OAuth2
      run: cd oauth2 && go vet -v ./...

    - name: Test Oauth2
      run: cd oauth2 && go test -v ./...

    - name: Build websmtp
      run: cd websmtp && go build -v ./...

    - name: Vet websmtp
      run: cd websmtp && go vet -v ./...

    - name: Test websmtp
      run: cd websmtp && go test -v ./...

    - name: Vet pkg/authapi
      run: cd pkg/authapi && go vet -v ./...

    - name: Test pkg/authapi
      run: cd pkg/authapi && go test -v ./...

    - name: Vet pkg/authdb
      run: cd pkg/authdb && go vet -v ./...

    - name: Test pkg/authdb
      run: cd pkg/authdb && go test -v ./...

    - name: Vet pkg/authmw
      run: cd pkg/authmw && go vet -v ./...

    - name: Test pkg/authmw
      run: cd pkg/authmw && go test -v ./...

    - name: Vet pkg/common
      run: cd pkg/common && go vet -v ./...

    - name: Test pkg/common
      run: cd pkg/common && go test -v ./...

    - name: Vet pkg/websmtp
      run: cd pkg/websmtp && go vet -v ./...

    - name: Test pkg/websmtp
      run: cd pkg/websmtp && go test -v ./...

  static:
    runs-on: ubuntu-latest
    steps:
    - uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1.1"
